<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'create_event' => [[], ['_controller' => 'App\\Controller\\EventController::createEvent'], [], [['text', '/events']], [], [], []],
    'get_events' => [[], ['_controller' => 'App\\Controller\\EventController::getEvents'], [], [['text', '/events']], [], [], []],
    'api_project_index' => [[], ['_controller' => 'App\\Controller\\ProjectController::index'], [], [['text', '/api/projects']], [], [], []],
    'api_project_create' => [[], ['_controller' => 'App\\Controller\\ProjectController::create'], [], [['text', '/api/projects']], [], [], []],
    'api_project_show' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projects']], [], [], []],
    'api_project_update' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projects']], [], [], []],
    'api_project_delete' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projects']], [], [], []],
    'api_app_login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/login']], [], [], []],
    'App\Controller\EventController::createEvent' => [[], ['_controller' => 'App\\Controller\\EventController::createEvent'], [], [['text', '/events']], [], [], []],
    'App\Controller\EventController::getEvents' => [[], ['_controller' => 'App\\Controller\\EventController::getEvents'], [], [['text', '/events']], [], [], []],
    'App\Controller\ProjectController::index' => [[], ['_controller' => 'App\\Controller\\ProjectController::index'], [], [['text', '/api/projects']], [], [], []],
    'App\Controller\ProjectController::create' => [[], ['_controller' => 'App\\Controller\\ProjectController::create'], [], [['text', '/api/projects']], [], [], []],
    'App\Controller\ProjectController::show' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projects']], [], [], []],
    'App\Controller\ProjectController::update' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projects']], [], [], []],
    'App\Controller\ProjectController::delete' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/projects']], [], [], []],
    'App\Controller\UserController::login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/login']], [], [], []],
];
